/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const rule =
    '@request.auth.id != "" && (sale.branch = "" || sale.branch.organization.organizationMemberships_via_organization.user ?= @request.auth.id)';

  const collection = new Collection({
    "id": "pbc_sale_con_usage",
    "name": "saleConsumableUsages",
    "type": "base",
    "system": false,
    "listRule": rule,
    "viewRule": rule,
    "createRule": rule,
    "updateRule": rule,
    "deleteRule": rule,
    "indexes": [
      "CREATE INDEX `idx_sale_con_usage_sale` ON `saleConsumableUsages` (`sale`)",
    ],
    "fields": [
      {
        "autogeneratePattern": "[a-z0-9]{15}",
        "hidden": false,
        "id": "text3208210256",
        "max": 15,
        "min": 15,
        "name": "id",
        "pattern": "^[a-z0-9]+$",
        "presentable": false,
        "primaryKey": true,
        "required": true,
        "system": true,
        "type": "text",
      },
      {
        "cascadeDelete": true,
        "collectionId": "pbc_2697449135",
        "hidden": false,
        "id": "rel_sale_con_sale",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "sale",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation",
      },
      {
        "cascadeDelete": false,
        "collectionId": "pbc_4092854851",
        "hidden": false,
        "id": "rel_sale_con_product",
        "maxSelect": 1,
        "minSelect": 0,
        "name": "product",
        "presentable": false,
        "required": true,
        "system": false,
        "type": "relation",
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text_sale_con_product_name",
        "max": 0,
        "min": 0,
        "name": "productName",
        "pattern": "",
        "presentable": true,
        "primaryKey": false,
        "required": true,
        "system": false,
        "type": "text",
      },
      {
        "hidden": false,
        "id": "number_sale_con_qty",
        "max": null,
        "min": 0,
        "name": "quantity",
        "onlyInt": false,
        "presentable": false,
        "required": true,
        "system": false,
        "type": "number",
      },
      {
        "autogeneratePattern": "",
        "hidden": false,
        "id": "text_sale_con_unit",
        "max": 0,
        "min": 0,
        "name": "unitLabel",
        "pattern": "",
        "presentable": false,
        "primaryKey": false,
        "required": false,
        "system": false,
        "type": "text",
      },
      {
        "hidden": false,
        "id": "number_sale_con_unit_cost",
        "max": null,
        "min": 0,
        "name": "unitCost",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number",
      },
      {
        "hidden": false,
        "id": "number_sale_con_cost",
        "max": null,
        "min": 0,
        "name": "cost",
        "onlyInt": false,
        "presentable": false,
        "required": false,
        "system": false,
        "type": "number",
      },
      {
        "hidden": false,
        "id": "autodate2990389176",
        "name": "created",
        "onCreate": true,
        "onUpdate": false,
        "presentable": false,
        "system": false,
        "type": "autodate",
      },
      {
        "hidden": false,
        "id": "autodate3332085495",
        "name": "updated",
        "onCreate": true,
        "onUpdate": true,
        "presentable": false,
        "system": false,
        "type": "autodate",
      },
    ],
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId("pbc_sale_con_usage");
  return app.delete(collection);
});
